In [2]:
# This will contain all imports required
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# Load Dataset
data=pd.read_csv("cicddos2019_dataset.csv")
data.head(3)

,Unnamed: 0,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,...,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Class
0,0,17,216631,6,0,2088.0,0.0,393.0,321.0,348.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UDP,Attack
1,1,17,2,2,0,802.0,0.0,401.0,401.0,401.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UDP,Attack
2,2,17,48,2,0,766.0,0.0,383.0,383.0,383.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UDP,Attack

In [ ]:
# Gather some info about data
listed=data.isna().sum()
listed[listed>0]

Series([], dtype: int64)

In [15]:
data.describe()

,Unnamed: 0,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,431371.000000,431371.000000,4.313710e+05,431371.000000,431371.000000,4.313710e+05,4.313710e+05,431371.000000,431371.000000,431371.000000,...,431371.000000,4.313710e+05,4.313710e+05,4.313710e+05,4.313710e+05,4.313710e+05,4.313710e+05,4.313710e+05,4.313710e+05,4.313710e+05
mean,126835.311055,13.948694,8.404856e+06,24.139117,2.472021,9.416956e+03,1.632896e+03,357.483674,294.721646,324.915327,...,21.893124,-2.315406e+07,3.370905e+04,2.563697e+04,6.757181e+04,1.868363e+04,2.449924e+06,4.983262e+05,2.971142e+06,1.993859e+06
std,87249.615423,4.966712,2.126596e+07,195.888896,56.370208,3.445253e+04,1.064056e+05,320.025929,273.298705,268.577313,...,54.559772,1.551755e+08,3.223119e+05,2.226543e+05,5.183739e+05,2.832011e+05,7.914010e+06,2.005164e+06,9.045327e+06,7.245561e+06
min,0.000000,0.000000,1.000000e+00,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,...,0.000000,-1.408238e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,53921.000000,6.000000,7.870000e+02,4.000000,0.000000,7.800000e+01,0.000000e+00,37.000000,6.000000,32.000000,...,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,107842.000000,17.000000,4.480400e+04,4.000000,0.000000,2.064000e+03,0.000000e+00,440.000000,330.000000,428.000000,...,3.000000,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,198357.500000,17.000000,3.002508e+06,16.000000,2.000000,5.160000e+03,0.000000e+00,516.000000,516.000000,516.000000,...,13.000000,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,306200.000000,17.000000,1.199987e+08,86666.000000,31700.000000,1.526642e+07,5.842950e+07,32120.000000,2131.000000,3015.290500,...,18766.000000,6.724045e+07,4.050800e+07,2.135244e+07,4.553668e+07,4.050800e+07,1.192194e+08,6.961402e+07,1.192194e+08,1.192194e+08

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431371 entries, 0 to 431370
Data columns (total 80 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Unnamed: 0                431371 non-null  int64
 1   Protocol                  431371 non-null  int64
 2   Flow Duration             431371 non-null  int64
 3   Total Fwd Packets         431371 non-null  int64
 4   Total Backward Packets    431371 non-null  int64
 5   Fwd Packets Length Total  431371 non-null  float64
 6   Bwd Packets Length Total  431371 non-null  float64
 7   Fwd Packet Length Max     431371 non-null  float64
 8   Fwd Packet Length Min     431371 non-null  float64
 9   Fwd Packet Length Mean    431371 non-null  float64
 10  Fwd Packet Length Std     431371 non-null  float64
 11  Bwd Packet Length Max     431371 non-null  float64
 12  Bwd Packet Length Min     431371 non-null  float64
 13  Bwd Packet Length Mean    431371 non-null  float64
 14  Bwd Packet Length Std     431371 non-null  float64
 15  Flow Bytes/s              431371 non-null  float64
 16  Flow Packets/s            431371 non-null  float64
 17  Flow IAT Mean             431371 non-null  float64
 18  Flow IAT Std              431371 non-null  float64
 19  Flow IAT Max              431371 non-null  float64
 20  Flow IAT Min              431371 non-null  float64
 21  Fwd IAT Total             431371 non-null  float64
 22  Fwd IAT Mean              431371 non-null  float64
 23  Fwd IAT Std               431371 non-null  float64
 24  Fwd IAT Max               431371 non-null  float64
 25  Fwd IAT Min               431371 non-null  float64
 26  Bwd IAT Total             431371 non-null  float64
 27  Bwd IAT Mean              431371 non-null  float64
 28  Bwd IAT Std               431371 non-null  float64
 29  Bwd IAT Max               431371 non-null  float64
 30  Bwd IAT Min               431371 non-null  float64
 31  Fwd PSH Flags             431371 non-null  int64
 32  Bwd PSH Flags             431371 non-null  int64
 33  Fwd URG Flags             431371 non-null  int64
 34  Bwd URG Flags             431371 non-null  int64
 35  Fwd Header Length         431371 non-null  int64
 36  Bwd Header Length         431371 non-null  int64
 37  Fwd Packets/s             431371 non-null  float64
 38  Bwd Packets/s             431371 non-null  float64
 39  Packet Length Min         431371 non-null  float64
 40  Packet Length Max         431371 non-null  float64
 41  Packet Length Mean        431371 non-null  float64
 42  Packet Length Std         431371 non-null  float64
 43  Packet Length Variance    431371 non-null  float64
 44  FIN Flag Count            431371 non-null  int64
 45  SYN Flag Count            431371 non-null  int64
 46  RST Flag Count            431371 non-null  int64
 47  PSH Flag Count            431371 non-null  int64
 48  ACK Flag Count            431371 non-null  int64
 49  URG Flag Count            431371 non-null  int64
 50  CWE Flag Count            431371 non-null  int64
 51  ECE Flag Count            431371 non-null  int64
 52  Down/Up Ratio             431371 non-null  float64
 53  Avg Packet Size           431371 non-null  float64
 54  Avg Fwd Segment Size      431371 non-null  float64
 55  Avg Bwd Segment Size      431371 non-null  float64
 56  Fwd Avg Bytes/Bulk        431371 non-null  int64
 57  Fwd Avg Packets/Bulk      431371 non-null  int64
 58  Fwd Avg Bulk Rate         431371 non-null  int64
 59  Bwd Avg Bytes/Bulk        431371 non-null  int64
 60  Bwd Avg Packets/Bulk      431371 non-null  int64
 61  Bwd Avg Bulk Rate         431371 non-null  int64
 62  Subflow Fwd Packets       431371 non-null  int64
 63  Subflow Fwd Bytes         431371 non-null  int64
 64  Subflow Bwd Packets       431371 non-null  int64
 65  Subflow Bwd Bytes         431371 non-null  int64
 66  Init Fwd Win Bytes        431371 non-null  int64
 67  Init Bwd Win Bytes        431371 non-null  int64
 68  Fwd Act Data Packets      431371 non-null  int64
 69  Fwd Seg Size Min          431371 non-null  int64
 70  Active Mean               431371 non-null  float64
 71  Active Std                431371 non-null  float64
 72  Active Max                431371 non-null  float64
 73  Active Min                431371 non-null  float64
 74  Idle Mean                 431371 non-null  float64
 75  Idle Std                  431371 non-null  float64
 76  Idle Max                  431371 non-null  float64
 77  Idle Min                  431371 non-null  float64
 78  Label                     431371 non-null  object
 79  Class                     431371 non-null  object
dtypes: float64(45), int64(33), object(2)
memory usage: 263.3+ MB

In [20]:
columns_list=data.columns
columns_list, len(columns_list)

(Index(['Unnamed: 0', 'Protocol', 'Flow Duration', 'Total Fwd Packets',
        'Total Backward Packets', 'Fwd Packets Length Total',
        'Bwd Packets Length Total', 'Fwd Packet Length Max',
        'Fwd Packet Length Min', 'Fwd Packet Length Mean',
        'Fwd Packet Length Std', 'Bwd Packet Length Max',
        'Bwd Packet Length Min', 'Bwd Packet Length Mean',
        'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
        'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
        'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max',
        'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
        'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags',
        'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
        'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
        'Packet Length Min', 'Packet Length Max', 'Packet Length Mean',
        'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
        'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
        'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
        'Avg Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
        'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate',
        'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate',
        'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets',
        'Subflow Bwd Bytes', 'Init Fwd Win Bytes', 'Init Bwd Win Bytes',
        'Fwd Act Data Packets', 'Fwd Seg Size Min', 'Active Mean', 'Active Std',
        'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max',
        'Idle Min', 'Label', 'Class'],
       dtype='object'),
 80)

In [27]:
data["Label"].value_counts()

Label
DrDoS_NTP        121368
TFTP              98917
Benign            97831
Syn               49373
UDP               18090
DrDoS_UDP         10420
UDP-lag            8872
MSSQL              8523
DrDoS_MSSQL        6212
DrDoS_DNS          3669
DrDoS_SNMP         2717
LDAP               1906
DrDoS_LDAP         1440
Portmap             685
NetBIOS             644
DrDoS_NetBIOS       598
UDPLag               55
WebDDoS              51
Name: count, dtype: int64

In [28]:
data["Class"].unique()

array(['Attack', 'Benign'], dtype=object)

In [ ]:
data["Class"].value_counts()

Class
Attack    333540
Benign     97831
Name: count, dtype: int64

In [31]:
data.shape

(431371, 80)

In [34]:
for col, dtype in data.dtypes.items():
    print(f"{col}: {dtype}")

Unnamed: 0: int64
Protocol: int64
Flow Duration: int64
Total Fwd Packets: int64
Total Backward Packets: int64
Fwd Packets Length Total: float64
Bwd Packets Length Total: float64
Fwd Packet Length Max: float64
Fwd Packet Length Min: float64
Fwd Packet Length Mean: float64
Fwd Packet Length Std: float64
Bwd Packet Length Max: float64
Bwd Packet Length Min: float64
Bwd Packet Length Mean: float64
Bwd Packet Length Std: float64
Flow Bytes/s: float64
Flow Packets/s: float64
Flow IAT Mean: float64
Flow IAT Std: float64
Flow IAT Max: float64
Flow IAT Min: float64
Fwd IAT Total: float64
Fwd IAT Mean: float64
Fwd IAT Std: float64
Fwd IAT Max: float64
Fwd IAT Min: float64
Bwd IAT Total: float64
Bwd IAT Mean: float64
Bwd IAT Std: float64
Bwd IAT Max: float64
Bwd IAT Min: float64
Fwd PSH Flags: int64
Bwd PSH Flags: int64
Fwd URG Flags: int64
Bwd URG Flags: int64
Fwd Header Length: int64
Bwd Header Length: int64
Fwd Packets/s: float64
Bwd Packets/s: float64
Packet Length Min: float64
Packet Length Max: float64
Packet Length Mean: float64
Packet Length Std: float64
Packet Length Variance: float64
FIN Flag Count: int64
SYN Flag Count: int64
RST Flag Count: int64
PSH Flag Count: int64
ACK Flag Count: int64
URG Flag Count: int64
CWE Flag Count: int64
ECE Flag Count: int64
Down/Up Ratio: float64
Avg Packet Size: float64
Avg Fwd Segment Size: float64
Avg Bwd Segment Size: float64
Fwd Avg Bytes/Bulk: int64
Fwd Avg Packets/Bulk: int64
Fwd Avg Bulk Rate: int64
Bwd Avg Bytes/Bulk: int64
Bwd Avg Packets/Bulk: int64
Bwd Avg Bulk Rate: int64
Subflow Fwd Packets: int64
Subflow Fwd Bytes: int64
Subflow Bwd Packets: int64
Subflow Bwd Bytes: int64
Init Fwd Win Bytes: int64
Init Bwd Win Bytes: int64
Fwd Act Data Packets: int64
Fwd Seg Size Min: int64
Active Mean: float64
Active Std: float64
Active Max: float64
Active Min: float64
Idle Mean: float64
Idle Std: float64
Idle Max: float64
Idle Min: float64
Label: object
Class: object

# Lets first handle the Data 
`* Split data into features and targets `

`* Then into train test split `

In [36]:
X=data.drop(columns=['Label', 'Class'])
y=data["Class"] # As we will be doing binary classfication for now and later we can go for multiclass 

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
print(X_train.shape , y_train.shape)
print(X_test.shape , y_test.shape)

(345096, 78) (345096,)
(86275, 78) (86275,)

# The dataset is imbalanced  `3.4 : 1`   percentage wise  77.3%  and 22.7 %

build a model on this imabalanced dataset first and then we will fix it

In [37]:
from sklearn.svm import LinearSVC

clf=LinearSVC()   # Going for default settings first then we can improve it 

clf.fit(X_train,y_train)

LinearSVC()

In [38]:
clf.score(X_test,y_test)

0.8471631411185164

In [41]:
y_preds=clf.predict(X_test)

In [52]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()

X=data.drop(columns=['Label', 'Class'])
y=data["Class"] # As we will be doing binary classfication for now and later we can go for multiclass 

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

rf.fit(X_train,y_train)

RandomForestClassifier()

In [53]:
rf.score(X_test,y_test)

0.9997681831353231

In [55]:
rf_preds=rf.predict(X_test)

In [57]:
rf_preds[:10]

array(['Attack', 'Attack', 'Benign', 'Attack', 'Attack', 'Attack',
       'Attack', 'Attack', 'Attack', 'Attack'], dtype=object)

In [59]:
np.array(y_test[:10])

array(['Attack', 'Attack', 'Benign', 'Attack', 'Attack', 'Attack',
       'Attack', 'Attack', 'Attack', 'Attack'], dtype=object)

In [60]:
from sklearn.linear_model import SGDClassifier

sg=SGDClassifier()

sg.fit(X_train,y_train)

sg.score(X_test,y_test)

0.9456041727035642

# Lets create a new model by simply making dataset from shuffled data

In [70]:
np.random.seed(42)
shuffled_Data=data.sample(frac=1).drop("Unnamed: 0",axis=1)
shuffled_Data.head()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Class
396344,17,449,98,0,42832.0,0.0,440.0,296.0,437.06122,20.465117,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP,Attack
24038,6,16696066,8,6,48.0,36.0,6.0,6.0,6.00000,0.000000,...,499965.0,706911.6,999827.0,103.0,7848067.5,1628737.8,8999759.0,6696376.0,Syn,Attack
170124,17,3008437,4,0,2064.0,0.0,516.0,516.0,516.00000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TFTP,Attack
178369,17,3112318,4,0,2064.0,0.0,516.0,516.0,516.00000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TFTP,Attack
8940,17,215106,6,0,2088.0,0.0,393.0,321.0,348.00000,35.088460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UDP,Attack

In [73]:
np.random.seed(42)
X=shuffled_Data.drop(columns=['Label','Class'])
y=shuffled_Data["Class"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

# Model Creation 
from sklearn.linear_model import SGDClassifier
sgdc=SGDClassifier()
sgdc.fit(X_train,y_train)
sgdc.score(X_test,y_test)

0.9546100825271226

Shuffling shows that the model accuracy decrease 
 `Could mean imbalnced migh reduce this more lets try to fix it  by making is close to balanced dataset`

#  Making Dataset Balanced

In [78]:
data[data['Class'] == "Benign"]

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Class
14937,6,9015834,6,0,0.0,0.0,0.0,0.0,0.00000,0.00000,...,28,3.009701e+06,0.000000,3009701.0,3009701.0,6006131.0,0.00,6006131.0,6006131.0,Benign
14938,0,113498356,52,0,0.0,0.0,0.0,0.0,0.00000,0.00000,...,0,1.533333e+01,28.810772,106.0,5.0,9458180.0,330788.75,9909241.0,9048680.0,Benign
14939,6,56638650,26,24,16880.0,2688.0,2797.0,6.0,649.23080,902.66284,...,20,7.457816e+04,107279.790000,289179.0,20805.0,9365196.0,1338180.00,10010988.0,6649735.0,Benign
14940,17,21234,2,2,64.0,256.0,32.0,32.0,32.00000,0.00000,...,20,0.000000e+00,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,Benign
14941,6,56653775,14,12,84.0,0.0,6.0,6.0,6.00000,0.00000,...,20,2.815900e+04,188.881970,28417.0,27941.0,9414137.0,1452975.90,10019426.0,6448290.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431366,6,550740,2,1,0.0,31.0,0.0,0.0,0.00000,0.00000,...,20,0.000000e+00,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,Benign
431367,6,337766,1,3,31.0,62.0,31.0,31.0,31.00000,0.00000,...,20,0.000000e+00,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,Benign
431368,6,228,1,2,0.0,0.0,0.0,0.0,0.00000,0.00000,...,20,0.000000e+00,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,Benign
431369,17,47709,2,2,86.0,194.0,43.0,43.0,43.00000,0.00000,...,20,0.000000e+00,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,Benign
431370,6,322010,30,33,5902.0,7444.0,1073.0,0.0,196.73334,353.03930,...,20,0.000000e+00,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,Benign

In [81]:
data=pd.read_csv("cicddos2019_dataset.csv")

In [82]:
data.head()

,Unnamed: 0,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,...,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Class
0,0,17,216631,6,0,2088.0,0.0,393.0,321.0,348.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UDP,Attack
1,1,17,2,2,0,802.0,0.0,401.0,401.0,401.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UDP,Attack
2,2,17,48,2,0,766.0,0.0,383.0,383.0,383.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UDP,Attack
3,3,17,107319,4,0,1398.0,0.0,369.0,330.0,349.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UDP,Attack
4,4,17,107271,4,0,1438.0,0.0,389.0,330.0,359.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UDP,Attack

In [ ]:
np.random.seed(42)
# Separate features & target
X = data.drop(columns=['Unnamed: 0', 'Label', 'Class'],axis=1)
y = data['Class']

# Recombine 
data = pd.concat([X, y], axis=1)

# split majority & minority 
df_attack = data[data['Class'] == "Attack"]
df_benign = data[data['Class'] == "Benign"]


# Down-sample the majority class

from sklearn.utils import resample

df_attack_down = resample(
    df_attack,
    replace=False,
    n_samples=len(df_benign),  
    random_state=42
)

# Combine & shuffle
df_balanced = pd.concat([df_attack_down, df_benign])
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

# Split back into X and y
X_bal = df_balanced.drop(columns=['Class'])
y_bal = df_balanced['Class']


# Three splits 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

Daataset balanced now lets start with the model

In [86]:
from sklearn.linear_model import SGDClassifier

sg2=SGDClassifier()
sg2.fit(X_train,y_train)
sg2.score(X_test,y_test)

0.8847522457258765

In [ ]:
from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)